// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: fastio/internal/pb/message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FASTIOSigmaMapValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	St []byte `protobuf:"bytes,1,opt,name=st,proto3" json:"st,omitempty"`
	C  uint64 `protobuf:"varint,2,opt,name=c,proto3" json:"c,omitempty"`
}

func (x *FASTIOSigmaMapValue) Reset() {
	*x = FASTIOSigmaMapValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fastio_internal_pb_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FASTIOSigmaMapValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FASTIOSigmaMapValue) ProtoMessage() {}

func (x *FASTIOSigmaMapValue) ProtoReflect() protoreflect.Message {
	mi := &file_fastio_internal_pb_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FASTIOSigmaMapValue.ProtoReflect.Descriptor instead.
func (*FASTIOSigmaMapValue) Descriptor() ([]byte, []int) {
	return file_fastio_internal_pb_message_proto_rawDescGZIP(), []int{0}
}

func (x *FASTIOSigmaMapValue) GetSt() []byte {
	if x != nil {
		return x.St
	}
	return nil
}

func (x *FASTIOSigmaMapValue) GetC() uint64 {
	if x != nil {
		return x.C
	}
	return 0
}

type FASTIOIDList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids [][]byte `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
}

func (x *FASTIOIDList) Reset() {
	*x = FASTIOIDList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fastio_internal_pb_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FASTIOIDList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FASTIOIDList) ProtoMessage() {}

func (x *FASTIOIDList) ProtoReflect() protoreflect.Message {
	mi := &file_fastio_internal_pb_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FASTIOIDList.ProtoReflect.Descriptor instead.
func (*FASTIOIDList) Descriptor() ([]byte, []int) {
	return file_fastio_internal_pb_message_proto_rawDescGZIP(), []int{1}
}

func (x *FASTIOIDList) GetIds() [][]byte {
	if x != nil {
		return x.Ids
	}
	return nil
}

type FASTIOUpdateToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	U []byte `protobuf:"bytes,1,opt,name=u,proto3" json:"u,omitempty"`
	E []byte `protobuf:"bytes,2,opt,name=e,proto3" json:"e,omitempty"`
}

func (x *FASTIOUpdateToken) Reset() {
	*x = FASTIOUpdateToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fastio_internal_pb_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FASTIOUpdateToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FASTIOUpdateToken) ProtoMessage() {}

func (x *FASTIOUpdateToken) ProtoReflect() protoreflect.Message {
	mi := &file_fastio_internal_pb_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FASTIOUpdateToken.ProtoReflect.Descriptor instead.
func (*FASTIOUpdateToken) Descriptor() ([]byte, []int) {
	return file_fastio_internal_pb_message_proto_rawDescGZIP(), []int{2}
}

func (x *FASTIOUpdateToken) GetU() []byte {
	if x != nil {
		return x.U
	}
	return nil
}

func (x *FASTIOUpdateToken) GetE() []byte {
	if x != nil {
		return x.E
	}
	return nil
}

type FASTIOSearchToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TW []byte `protobuf:"bytes,1,opt,name=t_w,json=tW,proto3" json:"t_w,omitempty"`
	KW []byte `protobuf:"bytes,2,opt,name=k_w,json=kW,proto3" json:"k_w,omitempty"`
	C  uint64 `protobuf:"varint,3,opt,name=c,proto3" json:"c,omitempty"`
}

func (x *FASTIOSearchToken) Reset() {
	*x = FASTIOSearchToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fastio_internal_pb_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FASTIOSearchToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FASTIOSearchToken) ProtoMessage() {}

func (x *FASTIOSearchToken) ProtoReflect() protoreflect.Message {
	mi := &file_fastio_internal_pb_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FASTIOSearchToken.ProtoReflect.Descriptor instead.
func (*FASTIOSearchToken) Descriptor() ([]byte, []int) {
	return file_fastio_internal_pb_message_proto_rawDescGZIP(), []int{3}
}

func (x *FASTIOSearchToken) GetTW() []byte {
	if x != nil {
		return x.TW
	}
	return nil
}

func (x *FASTIOSearchToken) GetKW() []byte {
	if x != nil {
		return x.KW
	}
	return nil
}

func (x *FASTIOSearchToken) GetC() uint64 {
	if x != nil {
		return x.C
	}
	return 0
}

var File_fastio_internal_pb_message_proto protoreflect.FileDescriptor

var file_fastio_internal_pb_message_proto_rawDesc = []byte{
	0x0a, 0x20, 0x66, 0x61, 0x73, 0x74, 0x69, 0x6f, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x33, 0x0a, 0x13, 0x46, 0x41, 0x53, 0x54, 0x49, 0x4f, 0x53, 0x69, 0x67, 0x6d,
	0x61, 0x4d, 0x61, 0x70, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x73, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x63, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x01, 0x63, 0x22, 0x20, 0x0a, 0x0c, 0x46, 0x41, 0x53, 0x54, 0x49,
	0x4f, 0x49, 0x44, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0c, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0x2f, 0x0a, 0x11, 0x46, 0x41, 0x53,
	0x54, 0x49, 0x4f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x0c,
	0x0a, 0x01, 0x75, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x75, 0x12, 0x0c, 0x0a, 0x01,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x65, 0x22, 0x43, 0x0a, 0x11, 0x46, 0x41,
	0x53, 0x54, 0x49, 0x4f, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x0f, 0x0a, 0x03, 0x74, 0x5f, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x74, 0x57,
	0x12, 0x0f, 0x0a, 0x03, 0x6b, 0x5f, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x6b,
	0x57, 0x12, 0x0c, 0x0a, 0x01, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x01, 0x63, 0x42,
	0x14, 0x5a, 0x12, 0x66, 0x61, 0x73, 0x74, 0x69, 0x6f, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_fastio_internal_pb_message_proto_rawDescOnce sync.Once
	file_fastio_internal_pb_message_proto_rawDescData = file_fastio_internal_pb_message_proto_rawDesc
)

func file_fastio_internal_pb_message_proto_rawDescGZIP() []byte {
	file_fastio_internal_pb_message_proto_rawDescOnce.Do(func() {
		file_fastio_internal_pb_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_fastio_internal_pb_message_proto_rawDescData)
	})
	return file_fastio_internal_pb_message_proto_rawDescData
}

var file_fastio_internal_pb_message_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_fastio_internal_pb_message_proto_goTypes = []interface{}{
	(*FASTIOSigmaMapValue)(nil), // 0: FASTIOSigmaMapValue
	(*FASTIOIDList)(nil),        // 1: FASTIOIDList
	(*FASTIOUpdateToken)(nil),   // 2: FASTIOUpdateToken
	(*FASTIOSearchToken)(nil),   // 3: FASTIOSearchToken
}
var file_fastio_internal_pb_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fastio_internal_pb_message_proto_init() }
func file_fastio_internal_pb_message_proto_init() {
	if File_fastio_internal_pb_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_fastio_internal_pb_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FASTIOSigmaMapValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fastio_internal_pb_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FASTIOIDList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fastio_internal_pb_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FASTIOUpdateToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fastio_internal_pb_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FASTIOSearchToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fastio_internal_pb_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fastio_internal_pb_message_proto_goTypes,
		DependencyIndexes: file_fastio_internal_pb_message_proto_depIdxs,
		MessageInfos:      file_fastio_internal_pb_message_proto_msgTypes,
	}.Build()
	File_fastio_internal_pb_message_proto = out.File
	file_fastio_internal_pb_message_proto_rawDesc = nil
	file_fastio_internal_pb_message_proto_goTypes = nil
	file_fastio_internal_pb_message_proto_depIdxs = nil
}
